blank_issues_enabled: true
contact_links:
  - name: Download the latest release
    url: https://github.com/CalemYoung/Dash/releases/latest
    about: Check that the problem still happens in the latest version.
