[general]
hotkey = "Alt+F"
show_on_screen_with_mouse = false

[ui]
program_width = 500
search_height = 70
results_height = 160
editor_height = 600
window_opacity = 0.97
search_font_size = 24
search_text_color = "#f3f4f7"
result_font_size = 14
result_text_color = "#e7e9ee"
description_font_size = 10
description_text_color = "#808080"
clock_font_size = 10
clock_day_text_color = "#f3f4f7"
clock_date_text_color = "#9da4b0"

[search]
max_results = 20
autocomplete = true
show_descriptions = true
show_command_tree = true

[shortcuts]
edit_selected_command = "Ctrl+Return"
new_command = "Ctrl+N"

[paths]
scripts_folder = "assets/scripts"
program_icon = "assets/icons/icon.png"
default_command_icon = "assets/icons/icon.png"
folder_icon = "assets/icons/folder.png"
file_icon = "assets/icons/file.png"
url_command_icon = "assets/icons/url.svg"
cache_folder = "assets/cache"
calculator_icon = "assets/icons/calculator.png"
no_result_icon = "assets/icons/no_result.png"
settings_command_icons = "assets/icons/settings.png"
quit_command_icon = "assets/icons/quit.png"
